### ISSUE TITLE
Cannot run suid programs

### ISSUE THREAD

**Issue by amon-ra** [multiarch/qemu-user-static#17] opened 2017-01-29 12:57 UTC
We are trying to run sudo inside the alpine docker image and it fails with:
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges

This may be related:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=683205

**Comment by hurricanehrndz** [comment] 2017-05-14 12:29
The problem is with the registration strings, it is missing the correct flags (`POC`, needs to be added as suffix) just as @amon-ra  mentions. I have verified that if you use the upstream[ binfmt configuration script ](https://github.com/qemu/qemu/blob/ecc1f5adeec4e3324d1b695a7c54e3967c526949/scripts/qemu-binfmt-conf.sh) that sudo works on emulated CPUs.

**Comment by moul** [comment] 2017-05-30 17:11
I just opened a PR (#23) which uses the official script to configure binfmt

**Comment by greyltc** [comment] 2018-10-09 19:15
I'm getting this today on version 2.12

**Comment by greyltc** [comment] 2018-10-14 11:02
Should this bug be fixed in 2.12?

**Comment by alejandro-perez** [comment] 2018-10-30 18:41
I also have this problem. Is there any way we can solve this?

**Comment by alejandro-perez** [comment] 2018-10-30 18:44
Appears to be solved with `docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes`

**Comment by junaruga** [comment] 2019-05-26 23:18
@amon-ra Could you solve this issue? are you fine to close this ticket?

**Comment by junaruga** [comment] 2019-08-06 13:04
Now better alternative.

```
$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

$ cat /proc/sys/fs/binfmt_misc/qemu-aarch64
enabled
interpreter /usr/bin/qemu-aarch64-static
flags: OCF
offset 0
magic 7f454c460201010000000000000000000200b700
mask ffffffffffffff00fffffffffffffffffeffffff

$ docker run --rm -it arm64v8/debian bash
```

```
# apt-get -y update
# apt-get -y install sudo

```

```
$ docker run --rm -it arm64v8/debian bash
```

Then below command works in the container. I do not know the warning "/bin/ls: /etc/sudoers: Function not implemented".

```
# apt-get -y update
# apt-get -y install sudo
# echo "test_user ALL = NOPASSWD: ALL" >> /etc/sudoers
# useradd -m test_user
# su - test_user
$ sudo ls -l /etc/sudoers 
/bin/ls: /etc/sudoers: Function not implemented
-r--r----- 1 root root 699 Aug  6 13:01 /etc/sudoers
```

I close this ticket. But feel free to reopen if you need something.
Thanks.

**Closed by junaruga** 2019-08-06 13:04 UTC
